[package]
name = "midnight-node-mock"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
prost = "0.13"
tokio = { version = "1", features = ["full"] }
tonic = "0.12"

[build-dependencies]
tonic-build = "0.12"
